export { Home } from "./panels/home/Home";
export { User } from "./panels/user/User";
export { Server } from "./panels/server/Server";
export { Gallery } from "./panels/gallery/Gallery";
export { Servers } from "./panels/servers/Servers";
export { Hypixel } from "./panels/hypixel/Hypixel";
export { Generator } from "./panels/generator/Generator";
export { Calculator } from "./panels/calculator/Calculator";
export { Status } from "./panels/status/Status";
